In [51]:
import pandas as pd

In [52]:
df = pd.read_csv('houses.csv')

In [53]:
df.head(2)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,...,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,...,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,...,"Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322

In [54]:
df.isnull().sum()

property_name        0
link                 0
society            591
price               76
rate                39
area                 0
areaWithType        57
bedRoom             57
bathroom            57
balcony             57
additionalRoom     455
address             13
noOfFloor           77
facing             370
agePossession       57
nearbyLocations    131
description          8
furnishDetails     301
features           370
rating             137
property_id          8
dtype: int64

In [55]:
df.drop(['property_id','link','description','rating'], axis=1, inplace=True)

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1044 non-null   str
 1   society          453 non-null    str
 2   price            968 non-null    str
 3   rate             1005 non-null   str
 4   area             1044 non-null   str
 5   areaWithType     987 non-null    str
 6   bedRoom          987 non-null    str
 7   bathroom         987 non-null    str
 8   balcony          987 non-null    str
 9   additionalRoom   589 non-null    str
 10  address          1031 non-null   str
 11  noOfFloor        967 non-null    str
 12  facing           674 non-null    str
 13  agePossession    987 non-null    str
 14  nearbyLocations  913 non-null    str
 15  furnishDetails   743 non-null    str
 16  features         674 non-null    str
dtypes: str(17)
memory usage: 138.8 KB

In [57]:
df['society'].value_counts()

society
Emaar MGF Marbella                     26
Vipul Tatvam Villa                     26
International City by SOBHA Phase 2    26
International City by Sobha Phase 1    23
Unitech Uniworld Resorts               13
                                       ..
Ansal Sushant Lok 2                     1
Godrej Meridien                         1
Sector 57 Huda                          1
Huda                                    1
Huda Floor                              1
Name: count, Length: 185, dtype: int64

In [58]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★','',str(name)).strip()).str.lower()

In [59]:
df.dropna(subset=['price'], inplace=True)

In [60]:
df['price'].value_counts()

price
3.5 Crore     19
5.5 Crore     17
6.5 Crore     16
6 Crore       14
5 Crore       13
              ..
3.8 Crore      1
7.45 Crore     1
7.42 Crore     1
6.09 Crore     1
2.98 Crore     1
Name: count, Length: 302, dtype: int64

In [61]:
def clean_price(price):
    price_str = str(price).lower().strip()
    if 'lac' in price_str:
        numeric_value = float(price_str.replace('lac', '').strip())
        return numeric_value * 0.01
    return price

df['price'] = df['price'].apply(clean_price)

In [62]:
df[df['price'].str.contains('lac', case=False, na=False)]

Empty DataFrame
Columns: [property_name, society, price, rate, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, noOfFloor, facing, agePossession, nearbyLocations, furnishDetails, features]
Index: []

In [63]:
df = df[df['price'].str.split().str.get(0) != 'Price']  # Remove header if it snuck into data

In [64]:
df['price'] = df['price'].str.split().str.get(0).astype(float)

In [65]:
df['price'].value_counts()# now the price is in crores

price
3.50    19
5.50    17
6.50    16
6.00    14
5.00    13
        ..
3.80     1
7.45     1
7.42     1
6.09     1
2.98     1
Name: count, Length: 237, dtype: int64

In [66]:
df.head(5)

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,furnishDetails,features
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...","['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1,5 Bedroom House for sale in Sector 21A Faridabad,nan,5.70,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ..."
2,10 Bedroom House for sale in Sushant Lok Phase 1,nan,2.10,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,nan,5.00,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,nan,3.00,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...","['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito..."

In [67]:
df['rate'] = df['rate'].str.split('/').str.get(0).str.replace(',','').str.replace('₹','').astype(float)

In [68]:
df['rate'].value_counts()

rate
22222.0    13
33333.0    11
11111.0    11
10000.0    10
37037.0     6
           ..
23870.0     1
20026.0     1
28787.0     1
12551.0     1
33129.0     1
Name: count, Length: 727, dtype: int64

In [69]:
df.rename(columns = {'rate':'price_per_sqft'}, inplace=True)

In [70]:
#area
import re
df['areaWithType'].value_counts()

areaWithType
Plot area 360(301.01 sq.m.)                                                                                     38
Plot area 300(250.84 sq.m.)                                                                                     27
Plot area 200(167.23 sq.m.)                                                                                     21
Plot area 502(419.74 sq.m.)                                                                                     18
Plot area 270(225.75 sq.m.)                                                                                     18
                                                                                                                ..
Plot area 214(178.93 sq.m.)Built Up area: 1500 sq.yards (1254.19 sq.m.)                                          1
Plot area 201(168.06 sq.m.)Built Up area: 180 sq.yards (150.5 sq.m.)Carpet area: 150 sq.yards (125.42 sq.m.)     1
Plot area 125(104.52 sq.m.)Built Up area: 115 sq.yards (96.15 sq.m.)Carpet area: 100 sq.yards (83.61 sq.m.)      1
Plot area 1800(167.23 sq.m.)Built Up area: 4800 sq.ft. (445.93 sq.m.)Carpet area: 3800 sq.ft. (353.03 sq.m.)     1
Plot area 1600(148.64 sq.m.)Built Up area: 1700 sq.ft. (157.94 sq.m.)Carpet area: 1650 sq.ft. (153.29 sq.m.)     1
Name: count, Length: 550, dtype: int64

In [71]:
def get_area(s):
    if s.split(' ')[2] == 'area:':
        return s.split(' ')[3]
    else:
        return s.split(' ')[2].split('(')[0]

In [72]:
df[df['areaWithType'].str.split(' ').str.get(2)!= 'area:']

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,furnishDetails,features
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...","['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1,5 Bedroom House for sale in Sector 21A Faridabad,nan,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ..."
2,10 Bedroom House for sale in Sushant Lok Phase 1,nan,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,nan,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,nan,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...","['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,4 Bedroom House for sale in Sector 26 Gurgaon,dlf city phase 1,5.50,30556.0,(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room","Sector 26 Gurgaon, Gurgaon, Haryana",2 Floors,North-East,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","['10 Light', 'No AC', 'No Bed', 'No Chimney', ...","['Feng Shui / Vaastu Compliant', 'High Ceiling..."
1040,3 Bedroom House for sale in DLF Phase 2,dlf city plots phase 2,4.25,31481.0,(125 sq.m.) Plot Area,Plot area 150(125.42 sq.m.),3 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"DLF Phase 2, Gurgaon, Haryana",2 Floors,North,10+ Year Old,"['Sahara Mall', 'Delhi Public School', 'Privat...",NaN,"['High Ceiling Height', 'Maintenance Staff', '..."
1041,3 Bedroom House for sale in Sector 26 Gurgaon,dlf city phase 1,4.50,33333.0,(125 sq.m.) Plot Area,Plot area 150(125.42 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,"Study Room,Servant Room","Sector 26 Gurgaon, Gurgaon, Haryana",2 Floors,East,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","['6 Fan', '20 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1042,3 Bedroom House for sale in Sector 26 Gurgaon,dlf city phase 1,3.25,33129.0,(91 sq.m.) Plot Area,Plot area 109(91.14 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,Study Room,"Sector 26 Gurgaon, Gurgaon, Haryana",2 Floors,West,10+ Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","['5 Fan', '16 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1043,3 Bedroom House for sale in Bissar,silverglades tarudhan valley golf resort,3.60,14815.0,(226 sq.m.) Plot Area,Plot area 270(225.75 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,"Pooja Room,Study Room,Servant Room,Others","Bissar, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'..."

In [73]:
df['area'] = df['areaWithType'].apply(get_area)

In [74]:
df[df['area']=='60Built']

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,furnishDetails,features
590,9 Bedroom House for sale in Sector 54 Gurgaon,suncity township,2.0,30968.0,60Built,Plot area 60Built Up area: 60 sq.m.Carpet area...,9 Bedrooms,9 Bathrooms,3 Balconies,Servant Room,NaN,11 Floors,North,1 to 5 Year Old,"['Sector 54 chowk metro station', 'Sector metr...","['1 Water Purifier', '9 Fan', '1 Fridge', '1 E...",['Internet/wi-fi connectivity']

In [75]:
df['area']=df['area'].str.replace('Built','')

In [76]:
df['area'] = df['area'].astype(float)

In [77]:
df.head(3)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,furnishDetails,features
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,290.0,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...","['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1,5 Bedroom House for sale in Sector 21A Faridabad,nan,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ..."
2,10 Bedroom House for sale in Sushant Lok Phase 1,nan,2.10,38251.0,61.0,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito..."

In [78]:
df['bedRoom']=df['bedRoom'].str.split(' ').str.get(0).astype(int)

In [79]:
df['balcony'] = df['balcony'].str.split(" ").str.get(0)

In [80]:
df['bathroom'] = df['bathroom'].str.split(" ").str.get(0).astype(int)

In [81]:
df['additionalRoom'].fillna('not available',inplace=True)

C:\Users\Hardik\AppData\Local\Temp\ipykernel_24608\3584107056.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['additionalRoom'].fillna('not available',inplace=True)

0                                    Servant Room
1              Store Room,Pooja Room,Servant Room
2                                    Servant Room
3                                    Servant Room
4                                          Others
                          ...
1039           Pooja Room,Study Room,Servant Room
1040                                   Study Room
1041                      Study Room,Servant Room
1042                                   Study Room
1043    Pooja Room,Study Room,Servant Room,Others
Name: additionalRoom, Length: 958, dtype: str

In [82]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [83]:
df['noOfFloor'] = df['noOfFloor'].str.split(' ').str.get(0)

In [84]:
df['facing'].fillna('NA', inplace=True)

C:\Users\Hardik\AppData\Local\Temp\ipykernel_24608\3102712490.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['facing'].fillna('NA', inplace=True)

0       North-East
1               NA
2             West
3            North
4             West
           ...
1039    North-East
1040         North
1041          East
1042          West
1043            NA
Name: facing, Length: 958, dtype: str

In [85]:
df.insert(loc=2,column='property_type',value = 'house')

In [86]:
df.insert(loc=5,column='sector',value = df['property_name'].str.split("in").str.get(1).str.replace('Gurgaon','').str.replace('Faridabad','').str.strip())

In [87]:
df.head(5)

,property_name,society,property_type,price,price_per_sqft,sector,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,furnishDetails,features
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,house,5.25,20115.0,Sector 70A,290.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...","['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1,5 Bedroom House for sale in Sector 21A Faridabad,nan,house,5.70,105751.0,Sector 21A,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ..."
2,10 Bedroom House for sale in Sushant Lok Phase 1,nan,house,2.10,38251.0,Sushant Lok Phase 1,61.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,nan,house,5.00,43066.0,Sector 54,129.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,nan,house,3.00,53763.0,Sushant Lok Phase 1,62.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...","['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito..."

In [88]:
df.drop(['property_name','address'], axis=1, inplace=True)

In [89]:
df.info()

<class 'pandas.DataFrame'>
Index: 958 entries, 0 to 1043
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   society          958 non-null    str
 1   property_type    958 non-null    str
 2   price            754 non-null    float64
 3   price_per_sqft   958 non-null    float64
 4   sector           958 non-null    object
 5   area             958 non-null    float64
 6   areaWithType     958 non-null    str
 7   bedRoom          958 non-null    int64
 8   bathroom         958 non-null    int64
 9   balcony          958 non-null    object
 10  additionalRoom   577 non-null    str
 11  noOfFloor        938 non-null    object
 12  facing           660 non-null    str
 13  agePossession    958 non-null    str
 14  nearbyLocations  843 non-null    str
 15  furnishDetails   726 non-null    str
 16  features         659 non-null    str
dtypes: float64(3), int64(2), object(3), str(9)
memory usage: 134.7+ KB

In [90]:
df.rename(columns={'noOfFloow':'floorNum'}, inplace=True)

In [91]:
df['area'].value_counts()

area
360.0     51
300.0     30
900.0     29
500.0     24
200.0     24
          ..
126.0      1
1935.0     1
214.0      1
201.0      1
125.0      1
Name: count, Length: 336, dtype: int64

In [92]:
df.rename(columns={'noOfFloor':'floorNum'}, inplace=True)

In [93]:
df.to_csv('cleaned_houses.csv', index=False)